"""Phase 1.4 — pilot: Phase 1.2 architecture trained on union(v2 + pseudo-Roboflow).

Path A — Step 2 in the pseudo-labeling pipeline. The user target is
**0.75 5-fold mean Dice** on v2 (segmentation track). Phase 1.2 plateaued
at 0.6946 ± 0.0205 on 213 trainable cases — confirmed data ceiling
across three architectures. Path A breaks the ceiling by expanding the
effective training set with high-quality pseudo-labels generated by
the Phase 1.2 5-fold ensemble itself (with optional Roboflow-bbox
oracle salvage).

Pilot scope: fold 0 only, train v2_fold0_train ∪ accepted-pseudo-Roboflow,
validate on v2_fold0_val (clean GT, untouched by pseudo-labels).

## Decision gates (per the data-ceiling pivot plan)

| Pilot Dice | Decision |
|---|---|
| ≥ 0.75 | Hit user target on a single fold (lucky-fold possible). Run 5-fold. |
| ≥ 0.71 | Real lift over Phase 1.2's 0.6946 baseline (+0.015 absolute, ~0.7σ above mean). Run 5-fold. |
| 0.69-0.71 | Statistical tie with Phase 1.2 (0.6946 ± 0.0205). Pseudo-labels not helping. Stop. |
| < 0.69 | Pseudo-labels actively HURTING (noise dominates). Tighten quality filter or stop. |

## Cfg

Identical to Phase 1.2 (resnet34 + EMA + boundary λ=0.05 + CLAHE-off +
roi_from_mask + batch=4 + lr_dec=1e-3 + 100 ep + patience=20) — the
ONLY change is `data.extra_train_csv` pointing to accepted pseudo-labels.
This makes the comparison clean: same architecture, same hyperparams,
same val set; only training-data set differs.

## Output

```
ai/models/checkpoints/encoder_unet/<TIMESTAMP>_<cfg_hash>/      # standard
experiments/results/phase1_4_pilot_fold0.json                   # sentinel
```

## Usage

```bash
python scripts/phase1_4_pilot.py
python scripts/phase1_4_pilot.py --fold 0 --pseudo-manifest data/processed/roboflow_pseudo_labels/manifest.csv
```
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

import pandas as pd
import yaml

from ai.training.splits import make_cv_folds
from ai.training.trainer import run

log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PSEUDO_MANIFEST = REPO_ROOT / "data" / "processed" / "roboflow_pseudo_labels" / "manifest.csv"
DEFAULT_PSEUDO_MASKS = REPO_ROOT / "data" / "processed" / "roboflow_pseudo_labels" / "masks"
ROBOFLOW_IMAGES_ROOT = REPO_ROOT / "data" / "raw" / "roboflow_scoliosis_v16" / "images"


def build_extra_train_csv(
    manifest_csv: Path,
    masks_dir: Path,
    roboflow_images_root: Path,
    out_csv: Path,
    strict_only: bool = False,
) -> int:
    """Read pseudo-label manifest, emit CSV with image_path + mask_path for accepted rows.

    Args:
        strict_only: if True, drop bbox-oracle-salvaged rows (n_vertebrae<14 or conf<0.70).
            Salvage rows have systematic under-coverage that degrades training Dice
            (confirmed by scripts/inspect_pseudo_labels.py: salvage mean pred vertebrae 12
            vs strict 17, 2× worse alignment to Roboflow bboxes).

    Returns the number of rows written.
    """
    manifest = pd.read_csv(manifest_csv)
    accepted = manifest[manifest["accepted"] == True].copy()
    if strict_only:
        accepted = accepted[
            (accepted["n_vertebrae"] >= 14)
            & (accepted["mean_fg_confidence"] >= 0.70)
        ].copy()

    def _image_path(stem: str, split: str) -> str:
        return str(roboflow_images_root / split / f"{stem}.jpg")

    accepted["image_path"] = accepted.apply(
        lambda r: _image_path(r["stem"], r["split"]), axis=1
    )
    accepted["multiclass_mask_path"] = accepted["stem"].apply(
        lambda s: str(masks_dir / f"{s}.png")
    )

    # Sanity-check files exist
    missing = []
    for _, r in accepted.iterrows():
        if not Path(r["image_path"]).exists():
            missing.append(("image", r["image_path"]))
        if not Path(r["multiclass_mask_path"]).exists():
            missing.append(("mask", r["multiclass_mask_path"]))
    if missing:
        raise FileNotFoundError(f"{len(missing)} pseudo-label files missing; first: {missing[:3]}")

    out_cols = ["stem", "split", "image_path", "multiclass_mask_path",
                "n_vertebrae", "mean_fg_confidence", "fg_frac"]
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    accepted[out_cols].to_csv(out_csv, index=False)
    return len(accepted)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--params", default="params.yaml")
    parser.add_argument("--out", default=None,
                        help="default: experiments/results/phase1_4_pilot_fold{F}[_strict].json")
    parser.add_argument("--fold", type=int, default=0, choices=[0, 1, 2, 3, 4])
    parser.add_argument("--pseudo-manifest", type=Path, default=DEFAULT_PSEUDO_MANIFEST)
    parser.add_argument("--pseudo-masks-dir", type=Path, default=DEFAULT_PSEUDO_MASKS)
    parser.add_argument("--roboflow-images-root", type=Path, default=ROBOFLOW_IMAGES_ROOT)
    parser.add_argument("--strict-only", action="store_true",
                        help="drop bbox-oracle-salvaged rows; use only strict-threshold accepts")
    parser.add_argument("--no-cache", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")

    if not args.pseudo_manifest.exists():
        raise FileNotFoundError(f"pseudo-label manifest missing: {args.pseudo_manifest}")

    with open(args.params) as f:
        cfg = yaml.safe_load(f)

    # Phase 1.2 cfg — same as scripts/phase1_2_5fold.py. Cfg-hash invariant.
    cfg["train"]["encoder_name"] = "resnet34"
    cfg["train"]["preprocess"]["clahe_mode"] = "off"
    cfg["train"]["preprocess"]["normalization"] = "div255"
    cfg["train"]["loss"]["boundary_lambda"] = 0.05
    cfg["train"]["ema"]["enabled"] = True
    cfg["train"]["preprocess"]["roi_crop"] = "from_mask"
    cfg["train"]["num_workers"] = 3

    # Build extra-train CSV from manifest
    csv_suffix = "_strict" if args.strict_only else ""
    extra_csv = REPO_ROOT / "data" / "processed" / "roboflow_pseudo_labels" / f"extra_train_rows{csv_suffix}.csv"
    n_extra = build_extra_train_csv(
        args.pseudo_manifest,
        args.pseudo_masks_dir,
        args.roboflow_images_root,
        extra_csv,
        strict_only=args.strict_only,
    )
    cfg["data"]["extra_train_csv"] = str(extra_csv)
    log.info("pseudo-label extra-train rows: %d → %s", n_extra, extra_csv)

    splits = make_cv_folds(
        clean_index_csv=cfg["data"]["clean_index"],
        test_holdout_csv=cfg["data"]["test_holdout"],
        n_splits=int(cfg["data"].get("cv_folds", 5)),
        seed=int(cfg["data"]["random_seed"]),
    )
    spec = splits[args.fold]
    log.info(
        "Phase 1.4 pilot fold %d (split_hash=%s): v2_train=%d + pseudo=%d ; v2_val=%d",
        args.fold,
        spec.hash(),
        len(spec.train_idx),
        n_extra,
        len(spec.val_idx),
    )

    t_start = time.time()
    result = run(cfg, spec=spec, use_cache=not args.no_cache)
    wall = time.time() - t_start

    summary = {
        "phase": "1.4-pilot",
        "fold": args.fold,
        "split_hash": spec.hash(),
        "v2_train_count": len(spec.train_idx),
        "pseudo_train_count": n_extra,
        "total_train_count": len(spec.train_idx) + n_extra,
        "v2_val_count": len(spec.val_idx),
        "best_val_dice": result["best_val_dice"],
        "best_source": result["best_source"],
        "total_time_sec": float(wall),
        "phase1_2_5fold_mean_reference": 0.6946,
        "phase1_2_5fold_std_reference": 0.0205,
        "user_target_dice": 0.75,
        "decision_gates": {
            ">= 0.75": "user target hit (single fold; verify with 5-fold)",
            "0.71 .. 0.75": "real lift over Phase 1.2 baseline; run 5-fold",
            "0.69 .. 0.71": "statistical tie with Phase 1.2; pseudo not helping; stop",
            "< 0.69": "pseudo HURTING; tighten filter or stop",
        },
        "run_dir": result["run_dir"],
    }

    if args.out is None:
        suffix = "_strict" if args.strict_only else ""
        out_path = Path(f"experiments/results/phase1_4_pilot_fold{args.fold}{suffix}.json")
    else:
        out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(summary, indent=2, default=str))

    log.info(
        "Phase 1.4 pilot fold %d: best_val_dice=%.4f vs Phase 1.2 baseline 0.6946 ± 0.0205 (Δ=%+.4f)",
        args.fold,
        result["best_val_dice"],
        result["best_val_dice"] - 0.6946,
    )
    log.info("wrote %s", out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
